
--Lab-4
--ALTER
--PART-B
select * from deposit_detail
--1 Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table
SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE';
--2 Delete Column AOPENDATE from the DEPOSIT_DETAIL table
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE;
--3 Rename Column CNAME to CustomerName.
SP_RENAME 'DEPOSIT_DETAIL.CNAME','CustomerName'

--PART-C
CREATE TABLE STUDENT_DETAIL(
	ENROLLMENT_NO VARCHAR(20),
	NAME VARCHAR(25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
);
--1 Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).
ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL;
--2 Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35)
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35);
--3 Change the data type DECIMAL to INT in CPI Column
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT;
--4 Rename Column Enrollment_No to ENO
SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO';
--5 Delete Column City from the student_detail table
ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY
--6 Change name of table student_detail to STUDENT_MASTER
SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER';

--DELETE,TRUNCATE,DROP
--PART-A
--1 Delete all the records of DEPOSIT_DETAIL table having amount greater than and equals to 4000
DELETE FROM DEPOSIT_DETAIL
WHERE AMOUNT>=4000;
--2 Delete all the accounts CHANDI BRANCH.
DELETE FROM DEPOSIT_DETAIL
WHERE BNAME='CHANDI';
--3 Delete all the accounts having account number (ANO) is greater than 105
DELETE FROM DEPOSIT_DETAIL
WHERE ANO>105
--4 Delete all the records of Deposit_Detail table. (Use Truncate)
TRUNCATE TABLE DEPOSIT_DETAIL;
--5 Remove Deposit_Detail table. (Use Drop)
DROP TABLE DEPOSIT_DETAIL;

--PART-B
CREATE TABLE EMPLOYEE_MASTER(
	EMPNO INT,
	EMPNAME VARCHAR(25),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES 
(101,'KEYUR','2002-01-05',12000.00,'RAJKOT'),
(102,'HARDIK','2004-02-15',14000.00,'AHMEDABAD'),
(103,'KAJAL','2006-03-14',15000.00,'BARODA'),
(104,'BHOOMI','2005-06-23',12500.00,'AHMEDABAD'),
(105,'HARMIT','2004-02-15',14000.00,'RAJKOT'),
(106,'MITESH','2001-09-25',5000.00,'JAMNAGAR'),
(107,'MEERA',NULL,7000.00,'MORBI'),
(108,'KISHAN','2003-02-06',10000.00,NULL);

delete from EMPLOYEE_MASTER where SALARY>=14000

delete from EMPLOYEE_MASTER where city='rajkot'

delete from EMPLOYEE_MASTER where JOININGDATE>'2007-1-1'

delete from EMPLOYEE_MASTER where JOININGDATE is null and EMPNAME <> null

delete from EMPLOYEE_MASTER where SALARY = (20000*0.5)

delete from EMPLOYEE_MASTER where CITY <> null

truncate table employee_master
select * from EMPLOYEE_MASTER

drop table EMPLOYEE_MASTER